name: Checks

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  python-checks:
    name: Python Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.0.0
        with:
          cache-dependency-glob: uv.lock

      - name: Install dependencies
        run: uv sync --group dev --locked

      - name: Run linters
        run: |
          uv run black --check .
          uv run ruff check .

      - name: Run tests
        run: uv run pytest
